#!/bin/bash
#

usage="Usage: weston-ready [-t timeout]"
timeout=0

function info() { echo "$@" >&2; }

function is_ready() {
surfaces_info=$(LayerManagerControl get surfaces)
cluster_info=$(su agl-driver -c "afm-util ps")

if [[ "$surfaces_info" == *"2000"* ]] && [[ "$surfaces_info" == *"2001"* ]]  && [[ "$cluster_info" == *"cluster-gauges"* ]]; then
  echo 1
else
  echo 0
fi
}

if [ $# -eq 2 ]; then
        if [ $1 = "-t" ]; then
                timeout=$(($2 * 10))
        else
                echo $usage
                exit 1
        fi                                                                       
fi                                                     
                                                                                 
                                                                                 
info "using timeout $timeout"                          
time=0                                                                           
rc=1                                                                             
while true; do                      
        ret=$(is_ready)             
        if [ $time -gt $timeout ]; then
                info "Timeout reached" 
                break                  
        elif [ ${ret} == "1" ]; then   
                info "Display Backend is ready is now ready"
                rc=0                                        
                systemctl restart display-manager           
                break                                       
        fi                                                  
        info "waiting..."
        if [ $timeout -gt 0 ]; then                         
                usleep 500000                               
        fi                                                  
        time=$(($time + 5))                                 
done
exit $rc
